#!/usr/bin/env php
<?php

/**
 * @author TJ Draper <tj@buzzingpixel.com>
 * @copyright 2019 BuzzingPixel, LLC
 * @license Apache-2.0
 */

use corbomite\di\Di;
use corbomite\twig\TwigEnvironment;

define('APP_BASE_PATH', __DIR__);

require_once 'vendor/autoload.php';

var_dump(Di::get(TwigEnvironment::class));
die;
